# https://docs.travis-ci.com/user/languages/python/
language: python

addons:
  apt:
    update: false

branches:
  only:
    - master

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:

  # Backward Compatibility in insured for release less than 1 year old.
  # https://pypi.org/project/tensorflow/#history
  matrix:
    - _TF_VERSION=1.9.0rc0 # Remove on Apr 28, 2019
    - _TF_VERSION=1.8.0 # Remove on Apr 28, 2019
    - _TF_VERSION=1.7.1 # Remove on May 08, 2019
    - _TF_VERSION=1.7.0 # Remove on Mar 29, 2019
    - _TF_VERSION=1.6.0 # Remove on Mar 01, 2019
    # - _TF_VERSION=1.5.1 # Remove on Mar 20, 2019
    # - _TF_VERSION=1.5.0 # Remove on Jan 26, 2019
    # - _TF_VERSION=1.4.1 # Remove on Dec 08, 2018
    # - _TF_VERSION=1.4.0 # Remove on Nov 01, 2018
    # - _TF_VERSION=1.3.0 # Remove on Aug 16, 2018
    # - _TF_VERSION=1.2.1 # Remove on Jun 30, 2018


install:
  - pip install tensorflow==$_TF_VERSION
  - pip install -r requirements-travis.txt


script:
  # units test
  # https://docs.pytest.org/en/latest/
  - pytest